export const daycareen = {
  "nav": {
    "whyUs": "Why Us",
    "programs": "Programs",
    "team": "Our Team",
    "schedule": "Schedule a Tour"
  },
  "footer": {
    "brandName": "Antelopa.preschool",
    "description": "The premier play-based preschool in Sacramento, dedicated to emotional safety and purposeful development.",
    "col1Title": "Programs",
    "col1Link1": "Infant Care",
    "col1Link2": "Toddler Program",
    "col1Link3": "Preschool & Pre-K",
    "col1Link4": "Tuition & Pricing",
    "col2Title": "About Us",
    "col2Link1": "Our Approach",
    "col2Link2": "Meet the Team",
    "col2Link3": "Safety Protocols",
    "col2Link4": "Parent FAQs",
    "col3Title": "Contact Info",
    "copyright": "© {{year}} Antelopa.preschool. All rights reserved.",
    "privacy": "Privacy Policy",
    "terms": "Terms of Service"
  },
  "hero": {
    "badge": "Sacramento's Premier Preschool",
    "titleLine1": "Where Little Minds Grow",
    "titleHighlight": "& Hearts Feel Safe",
    "subtitle": "More than just a daycare. We provide a calm, emotionally supportive environment where your child can thrive—giving you total peace of mind.",
    "ctaPrimary": "Schedule a Tour",
    "ctaSecondary": "Our Programs",
    "badgeReview": "120+ happy families"
  },
  "programs": {
    "heading": "Our Core <br/><span class='text-highlight'>Programs</span>",
    "subheading": "We conduct daily age-appropriate activities: from sensory development to school prep in a cozy home atmosphere.",
    "infantTitle": "Nest of Care",
    "infantAge": "Infants 6 - 18 months",
    "infantOutcome": "A gentle environment focused on sensory exploration.",
    "infantDesc": "Building secure attachment for our youngest learners.",
    "toddlerTitle": "Path of Discovery",
    "toddlerAge": "Toddlers 18 - 36 months",
    "toddlerOutcome": "Encouraging independence through nature play.",
    "toddlerDesc": "Developing motor skills and social skills in a group.",
    "prekTitle": "Creative Learning",
    "prekAge": "Preschool 3 - 5 years",
    "prekOutcome": "School readiness through creative expression.",
    "prekDesc": "Developing literacy and early math through play."
  },
  "photos": {
    "heading": "Our <br/><span class='text-highlight'>Photo</span> Reports",
    "subheading": "We capture the most precious moments of your child's day so you never miss a milestone.",
    "today": "Today's Album",
    "postTitle": "Daily Memories in the Cloud",
    "postDesc": "See how much fun we are having! We update our cloud gallery daily with cute, candid shots of our activities, crafts, and outdoor play.",
    "cloudLink": "Open Cloud Gallery"
  },
  "trust": {
    "licTitle": "Facility Lic# 343621813",
    "licDesc": "Fully licensed and compliant with California childcare standards.",
    "cprTitle": "100% CPR & First Aid Certified",
    "cprDesc": "Every staff member undergoes rigorous safety and medical training.",
    "bgTitle": "Comprehensive Background Checks",
    "bgDesc": "Strict vetting process including Live Scan fingerprinting.",
    "awardTitle": "Voted Sacramento's Best",
    "awardDesc": "Consistently highly rated by local parents for safety and care."
  },
  "whyUs": {
    "heading": "Philosophy & <br/> Mission",
    "subtitle": "At Antelopa.preschool, we believe education is not the filling of a pail, but the lighting of a fire. Rooted in gentleness and pedagogical excellence, our mission is to create an environment where children feel secure enough to explore the world.",
    "val1Title": "EMOTIONAL SAFETY",
    "val1Desc": "No child is ever left to 'cry it out'. We build trust first.",
    "val2Title": "TRANSPARENCY",
    "val2Desc": "Daily photo updates and open communication with parents.",
    "val3Title": "DEVELOPMENT",
    "val3Desc": "Purposeful play that prepares them for preschool and kindergarten.",
    "boxTitle": "A Cozy <br/> Environment",
    "boxDesc": "Our space is filled with natural light, prioritizing natural textures and organic materials to foster a calm, home-like feeling."
  },
  "gallery": {
    "heading": "Space of <br/><span class='text-highlight'>Inspiration</span>",
    "subtitle": "Spacious bright classrooms, natural materials, and a safe environment for development.",
    "img1": "Outdoor Nature Play Area",
    "img2": "Cozy Reading Corner",
    "img3": "Art Studio & Messy Play",
    "img4": "Infant Nap Room",
    "img5": "Family-Style Dining Area"
  },
  "team": {
    "heading": "Meet the Hearts Behind Antelopa.preschool",
    "subtitle": "Our teachers aren't just staff—they are career educators deeply committed to early childhood development.",
    "dirRole": "Center Director & Founder",
    "dirName": "Sarah Jenkins",
    "dirQuote": "When I couldn't find a preschool in Sacramento that offered both exceptional emotional care and rigorous academic preparation for my own daughter, I decided to build it. At Antelopa.preschool, we believe every child deserves a champion.",
    "dirCred1": "M.Ed. Early Childhood Edu",
    "dirCred2": "15+ Years Experience",
    "dirCred3": "Mother of Two",
    "t1Name": "Elena Rodriguez",
    "t1Role": "Lead Preschool Teacher",
    "t1Quote": "I love watching the exact moment a concept clicks for a child. My classroom is a place where mistakes are celebrated as proof that we are trying something new.",
    "t1Cred": "B.A. Child Development • 8 Years Exp",
    "t2Name": "David Chen",
    "t2Role": "Toddler Program Lead",
    "t2Quote": "Toddlers are natural scientists. I see my job as providing a safe laboratory for their endless experiments with gravity, physics, and friendships.",
    "t2Cred": "A.S. Early Education • 5 Years Exp",
    "t3Name": "Maria Santos",
    "t3Role": "Infant Room Lead",
    "t3Quote": "The first year of life shapes a child's worldview. I want every baby in my care to learn early on that the world is a gentle, responsive, and loving place.",
    "t3Cred": "Infant/Toddler Spec • 12 Years Exp",
    "hiringTitle": "Join Our Family",
    "hiringDesc": "We are always looking for passionate educators to join our Sacramento team.",
    "hiringLink": "View Careers"
  },
  "philosophy": {
    "heading": "We Don't Just Watch Children—We Help Them Grow",
    "subtitle": "Through purposeful play and a Reggio Emilia-inspired approach, we build confidence, curiosity, and kindergarten readiness.",
    "p1": "Many parents worry that daycare is just 'babysitting.' At Antelopa.preschool, every moment is a learning opportunity. We believe that children are naturally capable and curious researchers.",
    "p2": "Our curriculum isn't rigid; it emerges from the children's interests. If a toddler finds a fascinating bug outside, that week's lesson might pivot to explore insects, combining science, vocabulary, and art.",
    "li1": "Social-Emotional Growth",
    "li1Desc": "Learning to name feelings, navigate conflict, and show empathy.",
    "li2": "Academic Readiness",
    "li2Desc": "Pre-literacy and foundational math woven naturally into games.",
    "li3": "Creative Expression",
    "li3Desc": "Daily access to open-ended art, music, and dramatic play.",
    "rhythmTitle": "A Typical Day's Rhythm",
    "r1": "Arrival & Free Play",
    "r2": "Circle Time & Stories",
    "r3": "Morning Snack",
    "r4": "Outdoor Exploration",
    "r5": "Lunch Time",
    "r6": "Nap / Quiet Rest",
    "r7": "Music, Art, & Centers",
    "r8": "Pickup Begins"
  },
  "testimonials": {
    "heading": "Don't Just Take Our Word For It",
    "subtitle": "Hear from Sacramento families who trust us with their most precious gifts.",
    "t1Name": "Monica D.",
    "t1Loc": "Sacramento Midtown",
    "t1Quote": "My daughter runs there with joy every morning. Making the transition back to work was terrifying, but seeing how closely the teachers bonded with her made all my anxiety disappear.",
    "t1Prog": "Toddler Program Parent",
    "t2Name": "James & Sarah L.",
    "t2Loc": "East Sacramento",
    "t2Quote": "They treat my child like their own family. The cloud updates are the highlight of my workday. The clinical cleanliness and clear sick policies show they take safety incredibly seriously.",
    "t2Prog": "Infant Room Parents",
    "t3Name": "Elena T.",
    "t3Loc": "Land Park",
    "t3Quote": "Kindergarten was a refresher after this preschool. My son started elementary school reading full sentences and knowing how to respectfully express his feelings. Worth every penny.",
    "t3Prog": "Pre-K Graduate Parent"
  },
  "faq": {
    "heading": "Common Questions from Parents",
    "subtitle": "We believe in complete transparency. Don't see your question? Ask us during your tour.",
    "q1": "What are your child-to-teacher ratios?",
    "a1": "We strictly adhere to—and often exceed—California state licensing ratios. Our Infant room is 1:4, Toddler room is 1:6, and Preschool/Pre-K is 1:12. This ensures every child gets the individualized attention they need.",
    "q2": "What happens if my child is sick?",
    "a2": "To protect our community, children must be fever and symptom-free without medication for 24 hours before returning. If a child becomes ill during the day, they will rest in our comfortable, supervised office area while parents are contacted for immediate pickup.",
    "q3": "Are meals and snacks provided?",
    "a3": "Yes! We provide a nutritious morning snack, a balanced hot lunch, and an afternoon snack. We emphasize whole foods, fresh fruits, and vegetables, and we easily accommodate common allergies (we are a nut-free facility).",
    "q4": "How do you help new children transition?",
    "a4": "Every family receives a customized transition plan. We usually recommend a staggered start. We honor your child's feelings, never forcing separation, and use our cloud gallery to reassure you with photos as soon as they settle.",
    "q5": "What are your tuition rates and enrollment process?",
    "a5": "Tuition varies by program and schedule. We prefer to discuss pricing during your tour to ensure we find the right fit for your family. After a tour, you can secure your spot with a registration fee or join our waitlist if the desired room is currently full."
  },
  "cta": {
    "heading": "Ready to Give Them the Best Start?",
    "subtitle": "We know this is a big decision. Schedule a no-pressure tour to meet our teachers, see the classrooms in action, and see if we're the right fit for your family.",
    "availTitle": "Current Availability",
    "avail1": "Infant Room: Waitlist Only",
    "avail2": "Toddler Program: 2 Spots Left",
    "avail3": "Pre-K: Enrolling for Fall",
    "locTitle": "Location",
    "loc1": "1234 J Street",
    "loc2": "Sacramento, CA 95814 (Midtown)",
    "formTitle": "Request Your Tour",
    "fName": "Parent First Name",
    "lName": "Parent Last Name",
    "program": "Child's Age / Program",
    "pOpt1": "Select an option...",
    "pOpt2": "Infant (6 weeks - 18 mo)",
    "pOpt3": "Toddler (18 mo - 3 yrs)",
    "pOpt4": "Pre-K (3 - 5 yrs)",
    "pOpt5": "Unsure / Needs Assessment",
    "date": "Desired Start Date",
    "email": "Email Address",
    "submit": "See Pricing & Openings",
    "note": "No commitment required. We'll email you a link to choose a tour time."
  },
  "safety": {
    "heading": "We Treat Their <br/><span class='text-highlight'>Safety</span> as Our Highest Calling",
    "subtitle": "You'll know how your child is doing throughout the day with real-time updates, photos, and clear communication protocols.",
    "f1Title": "Daily Updates via Cloud",
    "f1Desc": "Get photos and meal updates sent directly to your phone throughout the day. Never wonder how they are doing.",
    "f2Title": "Strict Secure Entry",
    "f2Desc": "Doors are locked 24/7. Access is only granted to authorized family members via personalized PIN codes.",
    "f3Title": "Clinical-Grade Sanitization",
    "f3Desc": "Toys are sanitized daily, and high-touch surfaces are cleaned frequently to prevent the spread of germs.",
    "f4Title": "Clear Sick Child Policies",
    "f4Desc": "We strictly enforce our wellness policy to protect all children. If a child is sick, they stay home.",
    "appTag": "Just now via Cloud Gallery",
    "appMsg": "Leo just finished his lunch! 🍎",
    "cta": "Learn About Our Safety Protocols"
  }
};
